export interface SeedBankOption {
  id: number;
  name: string;
  shortCode: string;
  ifscPrefix: string;
}

export const seededBanks: SeedBankOption[] = [
  { id: 1, name: 'State Bank of India', shortCode: 'SBI', ifscPrefix: 'SBIN' },
  { id: 2, name: 'HDFC Bank', shortCode: 'HDFC', ifscPrefix: 'HDFC' },
  { id: 3, name: 'ICICI Bank', shortCode: 'ICICI', ifscPrefix: 'ICIC' },
  { id: 4, name: 'Axis Bank', shortCode: 'AXIS', ifscPrefix: 'UTIB' },
  { id: 5, name: 'Kotak Mahindra Bank', shortCode: 'KOTAK', ifscPrefix: 'KKBK' },
  { id: 6, name: 'Punjab National Bank', shortCode: 'PNB', ifscPrefix: 'PUNB' },
  { id: 7, name: 'Bank of Baroda', shortCode: 'BOB', ifscPrefix: 'BARB' },
  { id: 8, name: 'Canara Bank', shortCode: 'CANARA', ifscPrefix: 'CNRB' },
  { id: 9, name: 'Union Bank of India', shortCode: 'UNION', ifscPrefix: 'UBIN' },
  { id: 10, name: 'Bank of India', shortCode: 'BOI', ifscPrefix: 'BKID' },
  { id: 11, name: 'Indian Bank', shortCode: 'INDIAN', ifscPrefix: 'IDIB' },
  { id: 12, name: 'Central Bank of India', shortCode: 'CBI', ifscPrefix: 'CBIN' },
  { id: 13, name: 'Indian Overseas Bank', shortCode: 'IOB', ifscPrefix: 'IOBA' },
  { id: 14, name: 'UCO Bank', shortCode: 'UCO', ifscPrefix: 'UCBA' },
  { id: 15, name: 'Bank of Maharashtra', shortCode: 'BOM', ifscPrefix: 'MAHB' },
  { id: 16, name: 'Punjab & Sind Bank', shortCode: 'PSB', ifscPrefix: 'PSIB' },
  { id: 17, name: 'YES Bank', shortCode: 'YES', ifscPrefix: 'YESB' },
  { id: 18, name: 'IDFC First Bank', shortCode: 'IDFC', ifscPrefix: 'IDFB' },
  { id: 19, name: 'Federal Bank', shortCode: 'FEDERAL', ifscPrefix: 'FDRL' },
  { id: 20, name: 'South Indian Bank', shortCode: 'SIB', ifscPrefix: 'SIBL' },
  { id: 21, name: 'Karnataka Bank', shortCode: 'KBL', ifscPrefix: 'KARB' },
  { id: 22, name: 'Karur Vysya Bank', shortCode: 'KVB', ifscPrefix: 'KVBL' },
  { id: 23, name: 'City Union Bank', shortCode: 'CUB', ifscPrefix: 'CIUB' },
  { id: 24, name: 'Dhanlaxmi Bank', shortCode: 'DLB', ifscPrefix: 'DLXB' },
  { id: 25, name: 'Jammu & Kashmir Bank', shortCode: 'JKB', ifscPrefix: 'JAKA' },
  { id: 26, name: 'Lakshmi Vilas Bank', shortCode: 'LVB', ifscPrefix: 'LAVB' },
  { id: 27, name: 'Nainital Bank', shortCode: 'NTL', ifscPrefix: 'NTBL' },
  { id: 28, name: 'RBL Bank', shortCode: 'RBL', ifscPrefix: 'RATN' },
  { id: 29, name: 'IndusInd Bank', shortCode: 'INDUSIND', ifscPrefix: 'INDB' },
  { id: 30, name: 'Bandhan Bank', shortCode: 'BANDHAN', ifscPrefix: 'BDBL' },
  { id: 31, name: 'AU Small Finance Bank', shortCode: 'AU', ifscPrefix: 'AUBL' },
  { id: 32, name: 'Ujjivan Small Finance Bank', shortCode: 'UJJIVAN', ifscPrefix: 'UJVN' },
  { id: 33, name: 'Equitas Small Finance Bank', shortCode: 'EQUITAS', ifscPrefix: 'ESFB' },
  { id: 34, name: 'Suryoday Small Finance Bank', shortCode: 'SURYODAY', ifscPrefix: 'SURY' },
  { id: 35, name: 'Jana Small Finance Bank', shortCode: 'JANA', ifscPrefix: 'JSFB' },
  { id: 36, name: 'ESAF Small Finance Bank', shortCode: 'ESAF', ifscPrefix: 'ESAF' },
  { id: 37, name: 'Capital Small Finance Bank', shortCode: 'CAPITAL', ifscPrefix: 'CLBL' },
  { id: 38, name: 'Paytm Payments Bank', shortCode: 'PAYTM', ifscPrefix: 'PYTM' },
  { id: 39, name: 'Airtel Payments Bank', shortCode: 'AIRTEL', ifscPrefix: 'AIRP' },
  { id: 40, name: 'India Post Payments Bank', shortCode: 'IPPB', ifscPrefix: 'IPPB' },
  { id: 41, name: 'Fino Payments Bank', shortCode: 'FINO', ifscPrefix: 'FINO' },
  { id: 42, name: 'Andhra Bank', shortCode: 'ANDHRA', ifscPrefix: 'ANDB' },
  { id: 43, name: 'Corporation Bank', shortCode: 'CORP', ifscPrefix: 'CORP' },
  { id: 44, name: 'Syndicate Bank', shortCode: 'SYNDICATE', ifscPrefix: 'SYNB' },
  { id: 45, name: 'Allahabad Bank', shortCode: 'ALLAHABAD', ifscPrefix: 'ALLA' },
  { id: 46, name: 'Vijaya Bank', shortCode: 'VIJAYA', ifscPrefix: 'VIJB' },
  { id: 47, name: 'Dena Bank', shortCode: 'DENA', ifscPrefix: 'BKDN' },
  { id: 48, name: 'Oriental Bank of Commerce', shortCode: 'OBC', ifscPrefix: 'ORBC' },
  { id: 49, name: 'United Bank of India', shortCode: 'UNITED', ifscPrefix: 'UTBI' },
  { id: 50, name: 'Andhra Pradesh Grameena Vikas Bank', shortCode: 'APGVB', ifscPrefix: 'APGV' },
  { id: 51, name: 'Telangana Grameena Bank', shortCode: 'TGB', ifscPrefix: 'TGMB' },
  { id: 52, name: 'Deccan Grameena Bank', shortCode: 'DGB', ifscPrefix: 'DCGB' },
];
